#!/bin/sh
### BEGIN INIT INFO
# Provides:          dataload
# Required-Start:    mongod
# Required-Stop:
# Should-Start:
# Default-Start:     1 2 3 4 5
# Default-Stop:
# Short-Description: Load Data
# Description:       Load Data into mongod
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
. /lib/init/vars.sh

do_start () {
	# Load Data
	mongoimport /mongo-data/data.json
}

do_status () {
		return 0
}

case "$1" in
  start|"")
	do_start
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	# No-op
	;;
  status)
	do_status
	exit $?
	;;
  *)
	echo "Usage: dataload [start|stop|status]" >&2
	exit 3
	;;
esac

:

